branch-defaults:
  master:
    environment: createwebserver
global:
  application_name: Create web server
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.7 running PHP 7.0
  default_region: us-east-1
  profile: eb-cli
  sc: git
